
#Opotato
[alternatecurrent]
	"enable alternate current debug mode" = false
	#Compared with the 'Jump Over Fences' mod, the fence jumping function of this mod is better optimized.
	#I(Team Potato Coder, Kasualix) had experienced crash with 'Jump Over Fences' before, so I don't want to use it again and wrote this instead.
	#This is disabled by default, because this is not optimization & don't fit well with the concept of Opotato, but I do need this even for my personal use.
	#You can enable this if you like. (yea of course)
	"enable fence jump" = false

